# Petition parameters
ACTION_KIND = "Statement"  # "Petition", "Declaration", "Letter of Support"
ACTION_NAME = "Signatories"
ACTION_SHORT_DESCRIPTION = "Say yes to open source signing!"
ACTION_TEXT = '''
<p>
<u>Signatories</u> is a simple web-based program that allows a person to sign
an online petition, a declaration, a statement, or any form of communication
that requires community support. Designed for academics, signing is accomplished
by authenticating with an account at <a href="https://orcid.org">ORCID</a>.
</p>
<p>
The signatory may choose to remain anonymous. They may choose to add
their professional affiliation. After signing, they can modify their
signing preferences or remove their signature altogether. When the signatory's
name is visible, any user may click on it to inspect their ORCID profile.
</p>
<p>
By requiring an account at ORCID to sign, not only are bogus signatures
avoided, but this helps to limit participants to the academic community. An
ORCID account may sign at most once, and anonymous participants are assured to
have an ORCID account.
</p>
<p>
To see how it works, sign this statement by clicking the link below!
</p>
'''
ACTION_SLUG = ""  # subdirectory for URL
SORT_ALPHABETICAL = false

# Display image at top of page
USE_BANNER = false
BANNER_WIDTH = 35  # percentage of column width
BANNER_FILE = "banner.svg"  # file name with respect to static/img

# Set favicon (use "" for none)
FAVICON = "favicon.ico"  # file name with respect to static/img

# URL and name of a link displayed in the website footer,
# such as the association website
FOOTER_URL_NAME = "Planetary Research Cooperative"
FOOTER_URL = "https://coop.planetary-research.org/"
THANK_PRC = false

CONTACT_EMAIL = "tech@planetary-research.org"
